In [13]:
import cv2

resim = cv2.imread("kedi.jpg")#renkleri kullanmayacak 0(kanal 0)
cv2.imshow("beyza", resim)
#matrisini yazdırma
print(resim)
#boyut ögrenmek
print(resim.size)
print(resim.dtype)#hangi data tipinde
#resmin genişlik yükseklik ve kullandığı kanal sayısını göster
print(resim.shape)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[ 77 114 110]
  [ 78 115 111]
  [ 78 115 113]
  ...
  [195 201 200]
  [194 200 199]
  [194 200 199]]

 [[ 78 115 111]
  [ 78 115 111]
  [ 78 115 113]
  ...
  [196 202 201]
  [197 203 202]
  [197 203 202]]

 [[ 78 115 111]
  [ 78 115 111]
  [ 79 116 114]
  ...
  [193 198 197]
  [192 197 196]
  [192 197 196]]

 ...

 [[ 41  97 168]
  [ 37  96 166]
  [ 39  95 166]
  ...
  [ 12  52 104]
  [ 11  51 103]
  [ 12  52 104]]

 [[ 34  90 167]
  [ 31  89 164]
  [ 32  89 164]
  ...
  [ 18  58 110]
  [ 13  56 107]
  [ 11  54 105]]

 [[ 26  83 162]
  [ 23  80 159]
  [ 22  80 156]
  ...
  [ 21  61 113]
  [ 16  59 110]
  [ 12  55 106]]]
5760000
uint8
(1200, 1600, 3)


In [2]:
#brg piksel
kedi=cv2.imread("kedi.jpg")

# 230 asagı 80 sag renk pikselini alıyoruz.
print(kedi[(230,80)])
print("resim boyut: "+str(kedi.size))
print("resim özellik: "+str(kedi.shape))
print("resim veri tipi: "+str(kedi.dtype))
for i in range(100):
    kedi[i+20,100]=[0,0,255]
    

cv2.imshow("kedi",kedi)
cv2.waitKey(0)
cv2.destroyAllWindows()


NameError: name 'cv2' is not defined

In [50]:
#secili kısıma efekt
kedi=cv2.imread("43.jpg")
kedi[150:500,50:500,0]=150
#kedi[:,:,1]=255
#kedi[:,:,1]=150
cv2.imshow("kedi",kedi)
cv2.waitKey(0)
cv2.destroyAllWindows()

##### 

In [48]:
#secili kısıma yapıstır kırp efekt
kedi=cv2.imread("43.jpg")
resim=kedi[30:130,40:140]
kedi[0:100,0:100]=resim
kedi[0:400,0:250]=(0,200,200)
kedi[150:500,50:500,0]=150
#kedi[:,:,1]=255
#kedi[:,:,1]=150
cv2.imshow("kedi",kedi)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
import cv2
kedi=cv2.imread("f.jpg")
aynala=cv2.copyMakeBorder(kedi,125,125,300,300,cv2.BORDER_REFLECT)
uzat=cv2.copyMakeBorder(kedi,100,100,20,20,cv2.BORDER_REPLICATE)
tekrar=cv2.copyMakeBorder(kedi,125,125,300,300,cv2.BORDER_WRAP)
sarilan=cv2.copyMakeBorder(kedi,50,50,50,50,cv2.BORDER_CONSTANT ,value=(0,20,120))
#cv2.imshow("aynala",aynala)
#cv2.imshow("uzat",uzat)
cv2.imshow("sar",sarilan)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [25]:
#ağırlıklı toplama
import cv2
import numpy as np
kedi=cv2.imread("r.jpg")
print(kedi[100,200]+kedi[300,200])
kedi[50:100,200:250]=(220,240,250)
cv2.imshow("res",kedi)
cv2.waitKey(0)
cv2.destroyAllWindows()

[222 103 207]


In [26]:
#ağırlıklı toplama birbirleriyle birleştirme
import cv2
import numpy as np
resim1=cv2.imread("r.jpg")
resim2=cv2.imread("f.jpg")
toplam=cv2.add(resim1,resim2)
agietop=cv2.addWeighted(resim1,0.7,resim2,0.3,0)
cv2.imshow("topla",toplam)
cv2.imshow("res",agietop)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
#resimi grileştirme
import cv2
import numpy as np
resim1=cv2.imread("r.jpg")
yuk,gen,kanal=resim1.shape
print("orj",yuk,gen,kanal)
gri=cv2.cvtColor(resim1,cv2.COLOR_BGR2GRAY)
yuk1,gen1=gri.shape
print("orj",yuk1,gen1)
cv2.imshow("topla",resim1)
cv2.imshow("res",gri)
cv2.waitKey(0)
cv2.destroyAllWindows()

orj 600 600 3
orj 600 600


In [34]:
#buyut kucult
import cv2
import numpy as np
resim1=cv2.imread("r.jpg")
buyuk=cv2.pyrUp(resim1)
kucuk=cv2.pyrDown(resim1)
cv2.imshow("res",buyuk)
#cv2.imshow("res",kucuk)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [59]:
#gurultu azaltma için filtreleme
resim=cv2.imread("43.jpg")
meanf=cv2.blur(resim,(5,5))
median=cv2.medianBlur(resim,5)
gauss=cv2.GaussianBlur(resim,(5,5),0)

cv2.imshow("orj",resim)
cv2.imshow("ort",meanf)
cv2.imshow("medyan",median)
cv2.imshow("gauss",gauss)
print(resim[400,250])
print(meanf[400,250])
print(median[400,250])#****
print(gauss[400,250])
cv2.waitKey(0)
cv2.destroyAllWindows()

[ 64 109 153]
[ 65 108 154]
[ 66 109 155]
[ 65 109 155]


In [85]:
#genişlet-daralt gurultu
resim=cv2.imread("43.jpg")
kernel=np.ones((5,5),np.uint8)
erasion=cv2.erode(resim,kernel,iterations=2)
delation=cv2.dilate(resim,kernel,iterations=1)
#delation=cv2.dilate(erasion,kernel,iterations=1) gürültü azaltıp kalınlaştırma temiz görüntü elde etmek için
cv2.imshow("orj",resim)
cv2.imshow("r",erasion)
cv2.imshow("d",delation)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
#genişlet-daralt gurultu
image=cv2.imread("43.jpg")
kernel=np.ones((5,5),np.uint8)
opening=cv2.morphologyEx(image,cv2.MORPH_OPEN,kernel)
closing=cv2.morphologyEx(image,cv2.MORPH_CLOSE,kernel)
gradyan=cv2.morphologyEx(image,cv2.MORPH_GRADIENT,kernel)
tophat=cv2.morphologyEx(image,cv2.MORPH_TOPHAT,kernel)
blackhat=cv2.morphologyEx(image,cv2.MORPH_BLACKHAT,kernel)
cv2.imshow("orj",image)
cv2.imshow("o",opening)
cv2.imshow("c",closing)
cv2.imshow("g",gradyan)
cv2.imshow("t",tophat)
cv2.imshow("b",blackhat)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
image=cv2.imread("43.jpg")
resim=cv2.imread("r.jpg")
f=cv2.imread("f.jpg")
ret,thresh1=cv2.threshold(image,127,180,cv2.THRESH_BINARY)
ret,thresh2=cv2.threshold(image,150,250,cv2.THRESH_BINARY_INV)
ret,thresh3=cv2.threshold(image,127,180,cv2.THRESH_TRUNC)
ret,thresh4=cv2.threshold(image,127,180,cv2.THRESH_TOZERO)
ret,thresh5=cv2.threshold(image,150,250,cv2.THRESH_TOZERO_INV)
ret,thresh6=cv2.threshold(resim,150,250,cv2.THRESH_TOZERO_INV)
ret,thresh7=cv2.threshold(resim,150,250,cv2.THRESH_BINARY_INV)
ret,thresh8=cv2.threshold(f,150,250,cv2.THRESH_TOZERO_INV)
ret,thresh9=cv2.threshold(f,150,250,cv2.THRESH_BINARY_INV)
#cv2.imshow("orj",image)
#cv2.imshow("orj",resim)
#cv2.imshow("orj",f)
cv2.imshow("6",thresh6)
#cv2.imshow("7",thresh7)
#cv2.imshow("2",thresh2)
cv2.imshow("8",thresh8)
#cv2.imshow("9",thresh9)
#cv2.imshow("4",thresh4)
cv2.imshow("5",thresh5)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
image=cv2.imread("43.jpg",0)
resim=cv2.imread("r.jpg",0)
f=cv2.imread("f.jpg",0)
ret,thresh1=cv2.threshold(image,127,180,cv2.THRESH_BINARY)
thresh2=cv2.adaptiveThreshold(image,255,cv2.ADAPTIVE_THRESH_MEAN_C,cv2.THRESH_BINARY,11,2)
thresh3=cv2.adaptiveThreshold(image,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,11,2)

thresh4=cv2.adaptiveThreshold(resim,255,cv2.ADAPTIVE_THRESH_MEAN_C,cv2.THRESH_BINARY,11,2)
thresh5=cv2.adaptiveThreshold(resim,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,11,2)

thresh6=cv2.adaptiveThreshold(f,255,cv2.ADAPTIVE_THRESH_MEAN_C,cv2.THRESH_BINARY,11,2)
thresh7=cv2.adaptiveThreshold(f,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,11,2)
cv2.imshow("1",thresh1)
cv2.imshow("2",thresh2)
cv2.imshow("3",thresh3)
cv2.imshow("4",thresh4)
cv2.imshow("5",thresh5)
cv2.imshow("6",thresh6)
cv2.imshow("7",thresh7)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
import cv2
import numpy as np
image=cv2.imread("r.jpg",0)
blur=cv2.GaussianBlur(image,(3,3),0)
cv2.imshow("blur",blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
import cv2
import numpy as np
image=cv2.imread("r.jpg")
resim=cv2.imread("r.jpg")
bit_And=cv2.bitwise_and(image,resim)
cv2.imshow("bitand",bit_And)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [32]:
#iki resmin arasındaki fark
import cv2
resim=cv2.imread("43.jpg")
img=cv2.imread("r.jpg")
bir=cv2.subtract(resim,img)
cv2.imshow("s",bir)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import tensorflow as tf

# VGG16 modelini oluştur
vgg_model = tf.keras.applications.VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
for layer in vgg_model.layers:
    layer.trainable = False

# MobileNetV3-Small modelini oluştur
mobilenet_model = tf.keras.applications.MobileNetV3Small( input_shape=(224, 224, 3),  # Giriş şeklini ayarlayın
    minimalistic=False,
    include_top=True,
    weights="imagenet"
)
for layer in mobilenet_model.layers:
    layer.trainable = False

# İki modeli birleştir
combined_model = tf.keras.Sequential([
    vgg_model,
    mobilenet_model,
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')
])

# Modeli derle
combined_model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

# Veri yolu tanımları
egitim = r'C:\Users\06bey\zor\egitim'
val = r'C:\Users\06bey\zor\val'
test = r'C:\Users\06bey\zor\test'
preprocess_input = tf.keras.applications.mobilenet_v3.preprocess_input 

# Veri artırma
train_datagen = tf.keras.preprocessing.image.ImageDataGenerator(
    rescale=1./255,
    rotation_range=40,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest',
    preprocessing_function=preprocess_input 
)

train_generator = train_datagen.flow_from_directory(
    egitim, 
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',  # İkili sınıflandırma olduğunu belirtin
  
)

val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(
    rescale=1./255
)

val_generator = val_datagen.flow_from_directory(
    val, 
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',  # İkili sınıflandırma olduğunu belirtin
)

# Modeli eğit
history = combined_model.fit(
    train_generator,
    steps_per_epoch=len(train_generator),
    epochs=6,
    validation_data=val_generator,
    validation_steps=len(val_generator)
)

# Modeli kaydet
combined_model.save('combined_model.h5')


Found 1997 images belonging to 2 classes.


In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt

# VGG16 modelini yükleyelim
conv_base = tf.keras.applications.VGG16(weights=None, include_top=False, input_shape=(224, 224, 3))

# VGG16 modelinin belirli bir katmanına kadar olan ağırlıkları dondurma
conv_base.trainable = False

# MobilenetV3Small modelini yükleyelim
mobilenet_model = tf.keras.applications.MobileNetV3Small(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

# MobilenetV3Small modelinin belirli bir katmanına kadar olan ağırlıkları dondurma
for layer in mobilenet_model.layers:
    layer.trainable = False

resize_layer = tf.keras.layers.Conv2D(3, (1, 1), activation='relu')

# Modeli oluşturalım
model = tf.keras.Sequential([
    conv_base,
    resize_layer,
    tf.keras.layers.UpSampling2D(size=(32, 32)),  # Çıkış boyutunu (224, 224, 3) haline getiriyoruz
    mobilenet_model,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')
])

# Modeli derleyelim
model.compile(optimizer=tf.keras.optimizers.RMSprop(learning_rate=1e-5),
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

# Modelin özeti
model.summary()

# Veri yolları
egitim = r'C:\Users\06bey\zor\egitim'
val = r'C:\Users\06bey\zor\val'
test = r'C:\Users\06bey\zor\test' # Test veri yolu tanımlayalım

# Veri artırma ve veri akışlarını oluşturalım
train_datagen = tf.keras.preprocessing.image.ImageDataGenerator(
    rescale = 1.0 / 255,
    rotation_range=40,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

train_generator = train_datagen.flow_from_directory(
    egitim, 
    target_size=(224, 224),
    batch_size=32
)

val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(
    rescale=1./255
)

val_generator = val_datagen.flow_from_directory(
    val, 
    target_size=(224, 224),
    batch_size=32
)

# Modeli eğitelim
egit = model.fit(
    train_generator,
    steps_per_epoch=len(train_generator),
    epochs=5,
    validation_data=val_generator,
    validation_steps=len(val_generator)
)

# Eğitim sürecinde elde edilen metrikleri al
train_accuracy = egit.history['accuracy']
val_accuracy = egit.history['val_accuracy']
train_loss = egit.history['loss']
val_loss = egit.history['val_loss']

# Grafik oluştur
plt.figure(figsize=(10, 5))

# Doğruluk grafiği
plt.subplot(1, 2, 1)
plt.plot(train_accuracy, label='Training Accuracy', color='blue')
plt.plot(val_accuracy, label='Validation Accuracy', color='red')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Kayıp grafiği
plt.subplot(1, 2, 2)
plt.plot(train_loss, label='Training Loss', color='blue')
plt.plot(val_loss, label='Validation Loss', color='red')
plt.title('Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

# Grafikleri göster
plt.tight_layout()
plt.show()

# Modeli kaydet
model.save('yuz_ayirt_et.keras')

# Test veri akışını oluşturalım
test_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
    test,
    target_size=(224,224),
    batch_size=32,
)

# Test verisi üzerinde modeli değerlendirme
test_loss, test_acc = model.evaluate(test_generator)
print('Test accuracy:', test_acc)
